server:
  port: 8081

spring:
  datasource:
    url : jdbc:mysql://118.24.173.247:3306/conan_crawler?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false  
    username : root  
    password : guo@dong  
    driverClassName : com.mysql.jdbc.Driver
  kafka:
    producer:
      bootstrap-servers: 118.24.173.247:9092
    consumer:
      enable-auto-commit: true
      group-id: applog
      auto-offset-reset: latest
      bootstrap-servers: 118.24.173.247:9092
    
logging:
    path: ../log-pre
    level:
        org.springframework.web: TRACE
        guru.springframework.controllers: TRACE
        com.dy.springboot.server.mapper: DEBUG
        

