server:
  port: 7071
spring:
  datasource:
    url: jdbc:mysql://172.27.16.4:3306/conan_crawler?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: guo@dong
    driverClassName: com.mysql.jdbc.Driver
logging:
  path: ../log-pre7071
  level:
    org.springframework.web: TRACE
    guru.springframework.controllers: TRACE
    com.dy.springboot.server.mapper: DEBUG
conan:
  key-word-query-page-number: 5
  url:
    center: http://172.27.16.12:8080
    middleware: http://172.27.16.4:80
    node: 
      - http://172.27.16.2:8080
      - http://172.27.16.15:8080
      - http://172.27.16.14:8080
      - http://172.27.16.13:8080
      - http://172.27.16.11:8080
      - http://172.27.16.5:8080
      - http://172.27.16.10:8080
      - http://172.27.16.17:8080
      - http://172.27.16.6:8080
      - http://172.27.16.9:8080
    analysis: http://223.93.147.217:4433/PtBrain/listen