package com.conan.crawler.server.pre.entity;

import java.util.Date;

public class AnalysisV {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column analysis_v.id
     *
     * @mbg.generated Mon Apr 16 00:50:24 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column analysis_v.item_id
     *
     * @mbg.generated Mon Apr 16 00:50:24 CST 2018
     */
    private String itemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column analysis_v.item_title
     *
     * @mbg.generated Mon Apr 16 00:50:24 CST 2018
     */
    private String itemTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column analysis_v.catalog
     *
     * @mbg.generated Mon Apr 16 00:50:24 CST 2018
     */
    private String catalog;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column analysis_v.shop_name
     *
     * @mbg.generated Mon Apr 16 00:50:24 CST 2018
     */
    private String shopName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column analysis_v.seller_nick
     *
     * @mbg.generated Mon Apr 16 00:50:24 CST 2018
     */
    private String sellerNick;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column analysis_v.shop_star
     *
     * @mbg.generated Mon Apr 16 00:50:24 CST 2018
     */
    private String shopStar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column analysis_v.dsr_desc
     *
     * @mbg.generated Mon Apr 16 00:50:24 CST 2018
     */
    private String dsrDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column analysis_v.dsr_serv
     *
     * @mbg.generated Mon Apr 16 00:50:24 CST 2018
     */
    private String dsrServ;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column analysis_v.dsr_logi
     *
     * @mbg.generated Mon Apr 16 00:50:24 CST 2018
     */
    private String dsrLogi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column analysis_v.total
     *
     * @mbg.generated Mon Apr 16 00:50:24 CST 2018
     */
    private String total;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column analysis_v.buyer_nick
     *
     * @mbg.generated Mon Apr 16 00:50:24 CST 2018
     */
    private String buyerNick;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column analysis_v.first_review_time
     *
     * @mbg.generated Mon Apr 16 00:50:24 CST 2018
     */
    private String firstReviewTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column analysis_v.review_content
     *
     * @mbg.generated Mon Apr 16 00:50:24 CST 2018
     */
    private String reviewContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column analysis_v.is_super_vip
     *
     * @mbg.generated Mon Apr 16 00:50:24 CST 2018
     */
    private String isSuperVip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column analysis_v.buyer_star
     *
     * @mbg.generated Mon Apr 16 00:50:24 CST 2018
     */
    private String buyerStar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column analysis_v.crt_time
     *
     * @mbg.generated Mon Apr 16 00:50:24 CST 2018
     */
    private Date crtTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column analysis_v.crt_ip
     *
     * @mbg.generated Mon Apr 16 00:50:24 CST 2018
     */
    private String crtIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column analysis_v.shop_id
     *
     * @mbg.generated Mon Apr 16 00:50:24 CST 2018
     */
    private String shopId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column analysis_v.id
     *
     * @return the value of analysis_v.id
     *
     * @mbg.generated Mon Apr 16 00:50:24 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column analysis_v.id
     *
     * @param id the value for analysis_v.id
     *
     * @mbg.generated Mon Apr 16 00:50:24 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column analysis_v.item_id
     *
     * @return the value of analysis_v.item_id
     *
     * @mbg.generated Mon Apr 16 00:50:24 CST 2018
     */
    public String getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column analysis_v.item_id
     *
     * @param itemId the value for analysis_v.item_id
     *
     * @mbg.generated Mon Apr 16 00:50:24 CST 2018
     */
    public void setItemId(String itemId) {
        this.itemId = itemId == null ? null : itemId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column analysis_v.item_title
     *
     * @return the value of analysis_v.item_title
     *
     * @mbg.generated Mon Apr 16 00:50:24 CST 2018
     */
    public String getItemTitle() {
        return itemTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column analysis_v.item_title
     *
     * @param itemTitle the value for analysis_v.item_title
     *
     * @mbg.generated Mon Apr 16 00:50:24 CST 2018
     */
    public void setItemTitle(String itemTitle) {
        this.itemTitle = itemTitle == null ? null : itemTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column analysis_v.catalog
     *
     * @return the value of analysis_v.catalog
     *
     * @mbg.generated Mon Apr 16 00:50:24 CST 2018
     */
    public String getCatalog() {
        return catalog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column analysis_v.catalog
     *
     * @param catalog the value for analysis_v.catalog
     *
     * @mbg.generated Mon Apr 16 00:50:24 CST 2018
     */
    public void setCatalog(String catalog) {
        this.catalog = catalog == null ? null : catalog.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column analysis_v.shop_name
     *
     * @return the value of analysis_v.shop_name
     *
     * @mbg.generated Mon Apr 16 00:50:24 CST 2018
     */
    public String getShopName() {
        return shopName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column analysis_v.shop_name
     *
     * @param shopName the value for analysis_v.shop_name
     *
     * @mbg.generated Mon Apr 16 00:50:24 CST 2018
     */
    public void setShopName(String shopName) {
        this.shopName = shopName == null ? null : shopName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column analysis_v.seller_nick
     *
     * @return the value of analysis_v.seller_nick
     *
     * @mbg.generated Mon Apr 16 00:50:24 CST 2018
     */
    public String getSellerNick() {
        return sellerNick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column analysis_v.seller_nick
     *
     * @param sellerNick the value for analysis_v.seller_nick
     *
     * @mbg.generated Mon Apr 16 00:50:24 CST 2018
     */
    public void setSellerNick(String sellerNick) {
        this.sellerNick = sellerNick == null ? null : sellerNick.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column analysis_v.shop_star
     *
     * @return the value of analysis_v.shop_star
     *
     * @mbg.generated Mon Apr 16 00:50:24 CST 2018
     */
    public String getShopStar() {
        return shopStar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column analysis_v.shop_star
     *
     * @param shopStar the value for analysis_v.shop_star
     *
     * @mbg.generated Mon Apr 16 00:50:24 CST 2018
     */
    public void setShopStar(String shopStar) {
        this.shopStar = shopStar == null ? null : shopStar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column analysis_v.dsr_desc
     *
     * @return the value of analysis_v.dsr_desc
     *
     * @mbg.generated Mon Apr 16 00:50:24 CST 2018
     */
    public String getDsrDesc() {
        return dsrDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column analysis_v.dsr_desc
     *
     * @param dsrDesc the value for analysis_v.dsr_desc
     *
     * @mbg.generated Mon Apr 16 00:50:24 CST 2018
     */
    public void setDsrDesc(String dsrDesc) {
        this.dsrDesc = dsrDesc == null ? null : dsrDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column analysis_v.dsr_serv
     *
     * @return the value of analysis_v.dsr_serv
     *
     * @mbg.generated Mon Apr 16 00:50:24 CST 2018
     */
    public String getDsrServ() {
        return dsrServ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column analysis_v.dsr_serv
     *
     * @param dsrServ the value for analysis_v.dsr_serv
     *
     * @mbg.generated Mon Apr 16 00:50:24 CST 2018
     */
    public void setDsrServ(String dsrServ) {
        this.dsrServ = dsrServ == null ? null : dsrServ.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column analysis_v.dsr_logi
     *
     * @return the value of analysis_v.dsr_logi
     *
     * @mbg.generated Mon Apr 16 00:50:24 CST 2018
     */
    public String getDsrLogi() {
        return dsrLogi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column analysis_v.dsr_logi
     *
     * @param dsrLogi the value for analysis_v.dsr_logi
     *
     * @mbg.generated Mon Apr 16 00:50:24 CST 2018
     */
    public void setDsrLogi(String dsrLogi) {
        this.dsrLogi = dsrLogi == null ? null : dsrLogi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column analysis_v.total
     *
     * @return the value of analysis_v.total
     *
     * @mbg.generated Mon Apr 16 00:50:24 CST 2018
     */
    public String getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column analysis_v.total
     *
     * @param total the value for analysis_v.total
     *
     * @mbg.generated Mon Apr 16 00:50:24 CST 2018
     */
    public void setTotal(String total) {
        this.total = total == null ? null : total.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column analysis_v.buyer_nick
     *
     * @return the value of analysis_v.buyer_nick
     *
     * @mbg.generated Mon Apr 16 00:50:24 CST 2018
     */
    public String getBuyerNick() {
        return buyerNick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column analysis_v.buyer_nick
     *
     * @param buyerNick the value for analysis_v.buyer_nick
     *
     * @mbg.generated Mon Apr 16 00:50:24 CST 2018
     */
    public void setBuyerNick(String buyerNick) {
        this.buyerNick = buyerNick == null ? null : buyerNick.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column analysis_v.first_review_time
     *
     * @return the value of analysis_v.first_review_time
     *
     * @mbg.generated Mon Apr 16 00:50:24 CST 2018
     */
    public String getFirstReviewTime() {
        return firstReviewTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column analysis_v.first_review_time
     *
     * @param firstReviewTime the value for analysis_v.first_review_time
     *
     * @mbg.generated Mon Apr 16 00:50:24 CST 2018
     */
    public void setFirstReviewTime(String firstReviewTime) {
        this.firstReviewTime = firstReviewTime == null ? null : firstReviewTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column analysis_v.review_content
     *
     * @return the value of analysis_v.review_content
     *
     * @mbg.generated Mon Apr 16 00:50:24 CST 2018
     */
    public String getReviewContent() {
        return reviewContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column analysis_v.review_content
     *
     * @param reviewContent the value for analysis_v.review_content
     *
     * @mbg.generated Mon Apr 16 00:50:24 CST 2018
     */
    public void setReviewContent(String reviewContent) {
        this.reviewContent = reviewContent == null ? null : reviewContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column analysis_v.is_super_vip
     *
     * @return the value of analysis_v.is_super_vip
     *
     * @mbg.generated Mon Apr 16 00:50:24 CST 2018
     */
    public String getIsSuperVip() {
        return isSuperVip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column analysis_v.is_super_vip
     *
     * @param isSuperVip the value for analysis_v.is_super_vip
     *
     * @mbg.generated Mon Apr 16 00:50:24 CST 2018
     */
    public void setIsSuperVip(String isSuperVip) {
        this.isSuperVip = isSuperVip == null ? null : isSuperVip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column analysis_v.buyer_star
     *
     * @return the value of analysis_v.buyer_star
     *
     * @mbg.generated Mon Apr 16 00:50:24 CST 2018
     */
    public String getBuyerStar() {
        return buyerStar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column analysis_v.buyer_star
     *
     * @param buyerStar the value for analysis_v.buyer_star
     *
     * @mbg.generated Mon Apr 16 00:50:24 CST 2018
     */
    public void setBuyerStar(String buyerStar) {
        this.buyerStar = buyerStar == null ? null : buyerStar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column analysis_v.crt_time
     *
     * @return the value of analysis_v.crt_time
     *
     * @mbg.generated Mon Apr 16 00:50:24 CST 2018
     */
    public Date getCrtTime() {
        return crtTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column analysis_v.crt_time
     *
     * @param crtTime the value for analysis_v.crt_time
     *
     * @mbg.generated Mon Apr 16 00:50:24 CST 2018
     */
    public void setCrtTime(Date crtTime) {
        this.crtTime = crtTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column analysis_v.crt_ip
     *
     * @return the value of analysis_v.crt_ip
     *
     * @mbg.generated Mon Apr 16 00:50:24 CST 2018
     */
    public String getCrtIp() {
        return crtIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column analysis_v.crt_ip
     *
     * @param crtIp the value for analysis_v.crt_ip
     *
     * @mbg.generated Mon Apr 16 00:50:24 CST 2018
     */
    public void setCrtIp(String crtIp) {
        this.crtIp = crtIp == null ? null : crtIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column analysis_v.shop_id
     *
     * @return the value of analysis_v.shop_id
     *
     * @mbg.generated Mon Apr 16 00:50:24 CST 2018
     */
    public String getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column analysis_v.shop_id
     *
     * @param shopId the value for analysis_v.shop_id
     *
     * @mbg.generated Mon Apr 16 00:50:24 CST 2018
     */
    public void setShopId(String shopId) {
        this.shopId = shopId == null ? null : shopId.trim();
    }
}