package com.conan.crawler.server.pre.entity;

import java.util.Date;

public class KeyWordScanTb {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column key_word_scan_tb.id
     *
     * @mbg.generated Sun Apr 08 13:26:48 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column key_word_scan_tb.key_word
     *
     * @mbg.generated Sun Apr 08 13:26:48 CST 2018
     */
    private String keyWord;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column key_word_scan_tb.item_id
     *
     * @mbg.generated Sun Apr 08 13:26:48 CST 2018
     */
    private String itemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column key_word_scan_tb.item_title
     *
     * @mbg.generated Sun Apr 08 13:26:48 CST 2018
     */
    private String itemTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column key_word_scan_tb.user_number_id
     *
     * @mbg.generated Sun Apr 08 13:26:48 CST 2018
     */
    private String userNumberId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column key_word_scan_tb.shop_type
     *
     * @mbg.generated Sun Apr 08 13:26:48 CST 2018
     */
    private String shopType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column key_word_scan_tb.crt_time
     *
     * @mbg.generated Sun Apr 08 13:26:48 CST 2018
     */
    private Date crtTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column key_word_scan_tb.crt_user
     *
     * @mbg.generated Sun Apr 08 13:26:48 CST 2018
     */
    private String crtUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column key_word_scan_tb.crt_ip
     *
     * @mbg.generated Sun Apr 08 13:26:48 CST 2018
     */
    private String crtIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column key_word_scan_tb.status
     *
     * @mbg.generated Sun Apr 08 13:26:48 CST 2018
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column key_word_scan_tb.id
     *
     * @return the value of key_word_scan_tb.id
     *
     * @mbg.generated Sun Apr 08 13:26:48 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column key_word_scan_tb.id
     *
     * @param id the value for key_word_scan_tb.id
     *
     * @mbg.generated Sun Apr 08 13:26:48 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column key_word_scan_tb.key_word
     *
     * @return the value of key_word_scan_tb.key_word
     *
     * @mbg.generated Sun Apr 08 13:26:48 CST 2018
     */
    public String getKeyWord() {
        return keyWord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column key_word_scan_tb.key_word
     *
     * @param keyWord the value for key_word_scan_tb.key_word
     *
     * @mbg.generated Sun Apr 08 13:26:48 CST 2018
     */
    public void setKeyWord(String keyWord) {
        this.keyWord = keyWord == null ? null : keyWord.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column key_word_scan_tb.item_id
     *
     * @return the value of key_word_scan_tb.item_id
     *
     * @mbg.generated Sun Apr 08 13:26:48 CST 2018
     */
    public String getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column key_word_scan_tb.item_id
     *
     * @param itemId the value for key_word_scan_tb.item_id
     *
     * @mbg.generated Sun Apr 08 13:26:48 CST 2018
     */
    public void setItemId(String itemId) {
        this.itemId = itemId == null ? null : itemId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column key_word_scan_tb.item_title
     *
     * @return the value of key_word_scan_tb.item_title
     *
     * @mbg.generated Sun Apr 08 13:26:48 CST 2018
     */
    public String getItemTitle() {
        return itemTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column key_word_scan_tb.item_title
     *
     * @param itemTitle the value for key_word_scan_tb.item_title
     *
     * @mbg.generated Sun Apr 08 13:26:48 CST 2018
     */
    public void setItemTitle(String itemTitle) {
        this.itemTitle = itemTitle == null ? null : itemTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column key_word_scan_tb.user_number_id
     *
     * @return the value of key_word_scan_tb.user_number_id
     *
     * @mbg.generated Sun Apr 08 13:26:48 CST 2018
     */
    public String getUserNumberId() {
        return userNumberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column key_word_scan_tb.user_number_id
     *
     * @param userNumberId the value for key_word_scan_tb.user_number_id
     *
     * @mbg.generated Sun Apr 08 13:26:48 CST 2018
     */
    public void setUserNumberId(String userNumberId) {
        this.userNumberId = userNumberId == null ? null : userNumberId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column key_word_scan_tb.shop_type
     *
     * @return the value of key_word_scan_tb.shop_type
     *
     * @mbg.generated Sun Apr 08 13:26:48 CST 2018
     */
    public String getShopType() {
        return shopType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column key_word_scan_tb.shop_type
     *
     * @param shopType the value for key_word_scan_tb.shop_type
     *
     * @mbg.generated Sun Apr 08 13:26:48 CST 2018
     */
    public void setShopType(String shopType) {
        this.shopType = shopType == null ? null : shopType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column key_word_scan_tb.crt_time
     *
     * @return the value of key_word_scan_tb.crt_time
     *
     * @mbg.generated Sun Apr 08 13:26:48 CST 2018
     */
    public Date getCrtTime() {
        return crtTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column key_word_scan_tb.crt_time
     *
     * @param crtTime the value for key_word_scan_tb.crt_time
     *
     * @mbg.generated Sun Apr 08 13:26:48 CST 2018
     */
    public void setCrtTime(Date crtTime) {
        this.crtTime = crtTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column key_word_scan_tb.crt_user
     *
     * @return the value of key_word_scan_tb.crt_user
     *
     * @mbg.generated Sun Apr 08 13:26:48 CST 2018
     */
    public String getCrtUser() {
        return crtUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column key_word_scan_tb.crt_user
     *
     * @param crtUser the value for key_word_scan_tb.crt_user
     *
     * @mbg.generated Sun Apr 08 13:26:48 CST 2018
     */
    public void setCrtUser(String crtUser) {
        this.crtUser = crtUser == null ? null : crtUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column key_word_scan_tb.crt_ip
     *
     * @return the value of key_word_scan_tb.crt_ip
     *
     * @mbg.generated Sun Apr 08 13:26:48 CST 2018
     */
    public String getCrtIp() {
        return crtIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column key_word_scan_tb.crt_ip
     *
     * @param crtIp the value for key_word_scan_tb.crt_ip
     *
     * @mbg.generated Sun Apr 08 13:26:48 CST 2018
     */
    public void setCrtIp(String crtIp) {
        this.crtIp = crtIp == null ? null : crtIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column key_word_scan_tb.status
     *
     * @return the value of key_word_scan_tb.status
     *
     * @mbg.generated Sun Apr 08 13:26:48 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column key_word_scan_tb.status
     *
     * @param status the value for key_word_scan_tb.status
     *
     * @mbg.generated Sun Apr 08 13:26:48 CST 2018
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}