package com.conan.crawler.server.pre.entity;

import java.util.Date;

public class SellerTb {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller_tb.id
     *
     * @mbg.generated Sun Apr 08 13:26:48 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller_tb.user_number_id
     *
     * @mbg.generated Sun Apr 08 13:26:48 CST 2018
     */
    private String userNumberId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller_tb.shop_type
     *
     * @mbg.generated Sun Apr 08 13:26:48 CST 2018
     */
    private String shopType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller_tb.crt_user
     *
     * @mbg.generated Sun Apr 08 13:26:48 CST 2018
     */
    private String crtUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller_tb.crt_time
     *
     * @mbg.generated Sun Apr 08 13:26:48 CST 2018
     */
    private Date crtTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller_tb.crt_ip
     *
     * @mbg.generated Sun Apr 08 13:26:48 CST 2018
     */
    private String crtIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller_tb.status
     *
     * @mbg.generated Sun Apr 08 13:26:48 CST 2018
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seller_tb.id
     *
     * @return the value of seller_tb.id
     *
     * @mbg.generated Sun Apr 08 13:26:48 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seller_tb.id
     *
     * @param id the value for seller_tb.id
     *
     * @mbg.generated Sun Apr 08 13:26:48 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seller_tb.user_number_id
     *
     * @return the value of seller_tb.user_number_id
     *
     * @mbg.generated Sun Apr 08 13:26:48 CST 2018
     */
    public String getUserNumberId() {
        return userNumberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seller_tb.user_number_id
     *
     * @param userNumberId the value for seller_tb.user_number_id
     *
     * @mbg.generated Sun Apr 08 13:26:48 CST 2018
     */
    public void setUserNumberId(String userNumberId) {
        this.userNumberId = userNumberId == null ? null : userNumberId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seller_tb.shop_type
     *
     * @return the value of seller_tb.shop_type
     *
     * @mbg.generated Sun Apr 08 13:26:48 CST 2018
     */
    public String getShopType() {
        return shopType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seller_tb.shop_type
     *
     * @param shopType the value for seller_tb.shop_type
     *
     * @mbg.generated Sun Apr 08 13:26:48 CST 2018
     */
    public void setShopType(String shopType) {
        this.shopType = shopType == null ? null : shopType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seller_tb.crt_user
     *
     * @return the value of seller_tb.crt_user
     *
     * @mbg.generated Sun Apr 08 13:26:48 CST 2018
     */
    public String getCrtUser() {
        return crtUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seller_tb.crt_user
     *
     * @param crtUser the value for seller_tb.crt_user
     *
     * @mbg.generated Sun Apr 08 13:26:48 CST 2018
     */
    public void setCrtUser(String crtUser) {
        this.crtUser = crtUser == null ? null : crtUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seller_tb.crt_time
     *
     * @return the value of seller_tb.crt_time
     *
     * @mbg.generated Sun Apr 08 13:26:48 CST 2018
     */
    public Date getCrtTime() {
        return crtTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seller_tb.crt_time
     *
     * @param crtTime the value for seller_tb.crt_time
     *
     * @mbg.generated Sun Apr 08 13:26:48 CST 2018
     */
    public void setCrtTime(Date crtTime) {
        this.crtTime = crtTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seller_tb.crt_ip
     *
     * @return the value of seller_tb.crt_ip
     *
     * @mbg.generated Sun Apr 08 13:26:48 CST 2018
     */
    public String getCrtIp() {
        return crtIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seller_tb.crt_ip
     *
     * @param crtIp the value for seller_tb.crt_ip
     *
     * @mbg.generated Sun Apr 08 13:26:48 CST 2018
     */
    public void setCrtIp(String crtIp) {
        this.crtIp = crtIp == null ? null : crtIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seller_tb.status
     *
     * @return the value of seller_tb.status
     *
     * @mbg.generated Sun Apr 08 13:26:48 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seller_tb.status
     *
     * @param status the value for seller_tb.status
     *
     * @mbg.generated Sun Apr 08 13:26:48 CST 2018
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}