package com.conan.crawler.server.pre.entity;

import java.util.Date;

public class ShopScanTb {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_scan_tb.id
     *
     * @mbg.generated Sun Apr 08 13:26:48 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_scan_tb.shop_id
     *
     * @mbg.generated Sun Apr 08 13:26:48 CST 2018
     */
    private String shopId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_scan_tb.shop_name
     *
     * @mbg.generated Sun Apr 08 13:26:48 CST 2018
     */
    private String shopName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_scan_tb.seller_nick
     *
     * @mbg.generated Sun Apr 08 13:26:48 CST 2018
     */
    private String sellerNick;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_scan_tb.shop_star
     *
     * @mbg.generated Sun Apr 08 13:26:48 CST 2018
     */
    private String shopStar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_scan_tb.dsr_desc
     *
     * @mbg.generated Sun Apr 08 13:26:48 CST 2018
     */
    private String dsrDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_scan_tb.dsr_serv
     *
     * @mbg.generated Sun Apr 08 13:26:48 CST 2018
     */
    private String dsrServ;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_scan_tb.dsr_logi
     *
     * @mbg.generated Sun Apr 08 13:26:48 CST 2018
     */
    private String dsrLogi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_scan_tb.crt_user
     *
     * @mbg.generated Sun Apr 08 13:26:48 CST 2018
     */
    private String crtUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_scan_tb.crt_time
     *
     * @mbg.generated Sun Apr 08 13:26:48 CST 2018
     */
    private Date crtTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_scan_tb.crt_ip
     *
     * @mbg.generated Sun Apr 08 13:26:48 CST 2018
     */
    private String crtIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_scan_tb.status
     *
     * @mbg.generated Sun Apr 08 13:26:48 CST 2018
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_scan_tb.id
     *
     * @return the value of shop_scan_tb.id
     *
     * @mbg.generated Sun Apr 08 13:26:48 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_scan_tb.id
     *
     * @param id the value for shop_scan_tb.id
     *
     * @mbg.generated Sun Apr 08 13:26:48 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_scan_tb.shop_id
     *
     * @return the value of shop_scan_tb.shop_id
     *
     * @mbg.generated Sun Apr 08 13:26:48 CST 2018
     */
    public String getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_scan_tb.shop_id
     *
     * @param shopId the value for shop_scan_tb.shop_id
     *
     * @mbg.generated Sun Apr 08 13:26:48 CST 2018
     */
    public void setShopId(String shopId) {
        this.shopId = shopId == null ? null : shopId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_scan_tb.shop_name
     *
     * @return the value of shop_scan_tb.shop_name
     *
     * @mbg.generated Sun Apr 08 13:26:48 CST 2018
     */
    public String getShopName() {
        return shopName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_scan_tb.shop_name
     *
     * @param shopName the value for shop_scan_tb.shop_name
     *
     * @mbg.generated Sun Apr 08 13:26:48 CST 2018
     */
    public void setShopName(String shopName) {
        this.shopName = shopName == null ? null : shopName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_scan_tb.seller_nick
     *
     * @return the value of shop_scan_tb.seller_nick
     *
     * @mbg.generated Sun Apr 08 13:26:48 CST 2018
     */
    public String getSellerNick() {
        return sellerNick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_scan_tb.seller_nick
     *
     * @param sellerNick the value for shop_scan_tb.seller_nick
     *
     * @mbg.generated Sun Apr 08 13:26:48 CST 2018
     */
    public void setSellerNick(String sellerNick) {
        this.sellerNick = sellerNick == null ? null : sellerNick.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_scan_tb.shop_star
     *
     * @return the value of shop_scan_tb.shop_star
     *
     * @mbg.generated Sun Apr 08 13:26:48 CST 2018
     */
    public String getShopStar() {
        return shopStar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_scan_tb.shop_star
     *
     * @param shopStar the value for shop_scan_tb.shop_star
     *
     * @mbg.generated Sun Apr 08 13:26:48 CST 2018
     */
    public void setShopStar(String shopStar) {
        this.shopStar = shopStar == null ? null : shopStar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_scan_tb.dsr_desc
     *
     * @return the value of shop_scan_tb.dsr_desc
     *
     * @mbg.generated Sun Apr 08 13:26:48 CST 2018
     */
    public String getDsrDesc() {
        return dsrDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_scan_tb.dsr_desc
     *
     * @param dsrDesc the value for shop_scan_tb.dsr_desc
     *
     * @mbg.generated Sun Apr 08 13:26:48 CST 2018
     */
    public void setDsrDesc(String dsrDesc) {
        this.dsrDesc = dsrDesc == null ? null : dsrDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_scan_tb.dsr_serv
     *
     * @return the value of shop_scan_tb.dsr_serv
     *
     * @mbg.generated Sun Apr 08 13:26:48 CST 2018
     */
    public String getDsrServ() {
        return dsrServ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_scan_tb.dsr_serv
     *
     * @param dsrServ the value for shop_scan_tb.dsr_serv
     *
     * @mbg.generated Sun Apr 08 13:26:48 CST 2018
     */
    public void setDsrServ(String dsrServ) {
        this.dsrServ = dsrServ == null ? null : dsrServ.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_scan_tb.dsr_logi
     *
     * @return the value of shop_scan_tb.dsr_logi
     *
     * @mbg.generated Sun Apr 08 13:26:48 CST 2018
     */
    public String getDsrLogi() {
        return dsrLogi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_scan_tb.dsr_logi
     *
     * @param dsrLogi the value for shop_scan_tb.dsr_logi
     *
     * @mbg.generated Sun Apr 08 13:26:48 CST 2018
     */
    public void setDsrLogi(String dsrLogi) {
        this.dsrLogi = dsrLogi == null ? null : dsrLogi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_scan_tb.crt_user
     *
     * @return the value of shop_scan_tb.crt_user
     *
     * @mbg.generated Sun Apr 08 13:26:48 CST 2018
     */
    public String getCrtUser() {
        return crtUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_scan_tb.crt_user
     *
     * @param crtUser the value for shop_scan_tb.crt_user
     *
     * @mbg.generated Sun Apr 08 13:26:48 CST 2018
     */
    public void setCrtUser(String crtUser) {
        this.crtUser = crtUser == null ? null : crtUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_scan_tb.crt_time
     *
     * @return the value of shop_scan_tb.crt_time
     *
     * @mbg.generated Sun Apr 08 13:26:48 CST 2018
     */
    public Date getCrtTime() {
        return crtTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_scan_tb.crt_time
     *
     * @param crtTime the value for shop_scan_tb.crt_time
     *
     * @mbg.generated Sun Apr 08 13:26:48 CST 2018
     */
    public void setCrtTime(Date crtTime) {
        this.crtTime = crtTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_scan_tb.crt_ip
     *
     * @return the value of shop_scan_tb.crt_ip
     *
     * @mbg.generated Sun Apr 08 13:26:48 CST 2018
     */
    public String getCrtIp() {
        return crtIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_scan_tb.crt_ip
     *
     * @param crtIp the value for shop_scan_tb.crt_ip
     *
     * @mbg.generated Sun Apr 08 13:26:48 CST 2018
     */
    public void setCrtIp(String crtIp) {
        this.crtIp = crtIp == null ? null : crtIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_scan_tb.status
     *
     * @return the value of shop_scan_tb.status
     *
     * @mbg.generated Sun Apr 08 13:26:48 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_scan_tb.status
     *
     * @param status the value for shop_scan_tb.status
     *
     * @mbg.generated Sun Apr 08 13:26:48 CST 2018
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}