package com.conan.crawler.server.pre.mapper;

import com.conan.crawler.server.pre.entity.CommentTb;

public interface CommentTbMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_tb
     *
     * @mbg.generated Sun Apr 08 13:26:48 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_tb
     *
     * @mbg.generated Sun Apr 08 13:26:48 CST 2018
     */
    int insert(CommentTb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_tb
     *
     * @mbg.generated Sun Apr 08 13:26:48 CST 2018
     */
    int insertSelective(CommentTb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_tb
     *
     * @mbg.generated Sun Apr 08 13:26:48 CST 2018
     */
    CommentTb selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_tb
     *
     * @mbg.generated Sun Apr 08 13:26:48 CST 2018
     */
    int updateByPrimaryKeySelective(CommentTb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_tb
     *
     * @mbg.generated Sun Apr 08 13:26:48 CST 2018
     */
    int updateByPrimaryKey(CommentTb record);
}