package com.conan.crawler.server.pre.mapper;

import java.util.List;

import com.conan.crawler.server.pre.entity.KeyWordTb;

public interface KeyWordTbMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table key_word_tb
     *
     * @mbg.generated Sun Apr 08 13:26:48 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table key_word_tb
     *
     * @mbg.generated Sun Apr 08 13:26:48 CST 2018
     */
    int insert(KeyWordTb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table key_word_tb
     *
     * @mbg.generated Sun Apr 08 13:26:48 CST 2018
     */
    int insertSelective(KeyWordTb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table key_word_tb
     *
     * @mbg.generated Sun Apr 08 13:26:48 CST 2018
     */
    KeyWordTb selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table key_word_tb
     *
     * @mbg.generated Sun Apr 08 13:26:48 CST 2018
     */
    int updateByPrimaryKeySelective(KeyWordTb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table key_word_tb
     *
     * @mbg.generated Sun Apr 08 13:26:48 CST 2018
     */
    int updateByPrimaryKey(KeyWordTb record);
    
    List<KeyWordTb> selectAll();
    List<KeyWordTb> selectByStatus(String status);
}